# Generated by Django 5.0.7 on 2024-08-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
