# Generated by Django 5.0.7 on 2024-08-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
